name: Build Windows App and Release

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    
jobs:
  Build_Windows:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.10.0
        with:
          channel: 'stable'

      - name: Install App dependencies
        run: flutter pub get

      - name: Build Windows app
        run: flutter build windows --release

      - name: Retrieve Windows app
        uses: actions/upload-artifact@v3
        with:
          name: YouFetch_Win
          path: build/windows/runner/Release

  Build_Linux:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.10.0
        with:
          channel: 'stable'

      - name: Install App dependencies
        run: flutter pub get

      - name: Install Build Tools      
        run: sudo apt install ninja-build  pkg-config

      - name: Build Linux app
        run: flutter build linux --release

      - name: Retrieve Linux app
        uses: actions/upload-artifact@v3
        with:
          name: YouFetch_Linux
          path: build/linux/x64/release/bundle




      # - name: Create Release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PAT }}
      #   with:
      #     tag_name: v1.0.1 
      #     release_name: Release v1.0.1  
      #     draft: true
      #     prerelease: true