name: Build Windows App

on:
  push:
    branches: 
    - main
  pull_request:
    branches: 
    - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.PAT}} 

      - name: Set up Flutter
        uses: subosito/flutter-action@v1.6.0

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows app
        run: flutter build windows

      - name: Retrieve Windows app
        uses: actions/upload-artifact@v2
        with:
          name: my_windows_app
          path: build/windows
