name: Build Windows App

on:
  pull_request:
    branches:
      - master
      
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows app
        run: flutter build windows

      - name: Retrieve Windows app
        uses: actions/upload-artifact@v2
        with:
          name: my_windows_app
          path: build/windows
